default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bitbot_development

test: &test
  <<: *default
  database: bitbot_test

production:
  <<: *default
  database: bitbot_production
  username: bitbot
  password: <%= ENV['BITBOT_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
